services:
  fix-permissions:
    image: alpine
    container_name: fix_stream_permissions
    user: root
    volumes:
      - ./streams:/streams
    command: chmod 777 /streams

  streamvision:
    image: codebyamrit/streamvision:latest
    container_name: streamvision_app
    depends_on:
      fix-permissions:
        condition: service_completed_successfully
    command: [ "node", "cluster.js" ]
    expose:
      - "3000"
    env_file:
      - .env
    restart: unless-stopped
    tmpfs:
      - /tmp
    volumes:
      - ./streams:/usr/src/app/streams
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.streamvision.rule=Host(`cctvweblink.in`)"
      - "traefik.http.routers.streamvision.entrypoints=https"
      - "traefik.http.routers.streamvision.tls.certresolver=letsencrypt"
      - "traefik.http.services.streamvision.loadbalancer.server.port=3000"
      - "logging.service=streamvision"
