services:
  streamvision:
    image: codebyamrit/streamvision:latest
    container_name: streamvision_app
    command: ["node", "cluster.js"]
    expose:
      - "3000"
    env_file:
      - .env
    restart: unless-stopped
    tmpfs:
      - /tmp
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - streamvision-net
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.streamvision.rule=Host(`cctvcameralive.in`)"
      - "traefik.http.routers.streamvision.entrypoints=websecure"
      - "traefik.http.routers.streamvision.tls.certresolver=letsencrypt"
      - "traefik.http.services.streamvision.loadbalancer.server.port=3000"


networks:
  streamvision-net:

  proxy:
    external: true